# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joncrall/code/hotspotter/_frontend/MainSkel.ui'
#
# Created: Mon Dec  9 12:43:44 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainSkel(object):
    def setupUi(self, mainSkel):
        mainSkel.setObjectName(_fromUtf8("mainSkel"))
        mainSkel.resize(927, 573)
        self.centralwidget = QtGui.QWidget(mainSkel)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.root_hlayout = QtGui.QHBoxLayout()
        self.root_hlayout.setObjectName(_fromUtf8("root_hlayout"))
        self.tablesTabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablesTabWidget.sizePolicy().hasHeightForWidth())
        self.tablesTabWidget.setSizePolicy(sizePolicy)
        self.tablesTabWidget.setObjectName(_fromUtf8("tablesTabWidget"))
        self.image_view = QtGui.QWidget()
        self.image_view.setMinimumSize(QtCore.QSize(445, 0))
        self.image_view.setObjectName(_fromUtf8("image_view"))
        self.gridLayout_3 = QtGui.QGridLayout(self.image_view)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.image_TBL = QtGui.QTableWidget(self.image_view)
        self.image_TBL.setObjectName(_fromUtf8("image_TBL"))
        self.image_TBL.setColumnCount(0)
        self.image_TBL.setRowCount(0)
        self.verticalLayout.addWidget(self.image_TBL)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tablesTabWidget.addTab(self.image_view, _fromUtf8(""))
        self.chip_view = QtGui.QWidget()
        self.chip_view.setObjectName(_fromUtf8("chip_view"))
        self.gridLayout_4 = QtGui.QGridLayout(self.chip_view)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chip_TBL = QtGui.QTableWidget(self.chip_view)
        self.chip_TBL.setObjectName(_fromUtf8("chip_TBL"))
        self.chip_TBL.setColumnCount(0)
        self.chip_TBL.setRowCount(0)
        self.verticalLayout_3.addWidget(self.chip_TBL)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tablesTabWidget.addTab(self.chip_view, _fromUtf8(""))
        self.result_view = QtGui.QWidget()
        self.result_view.setObjectName(_fromUtf8("result_view"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.result_view)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.res_TBL = QtGui.QTableWidget(self.result_view)
        self.res_TBL.setObjectName(_fromUtf8("res_TBL"))
        self.res_TBL.setColumnCount(0)
        self.res_TBL.setRowCount(0)
        self.verticalLayout_4.addWidget(self.res_TBL)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tablesTabWidget.addTab(self.result_view, _fromUtf8(""))
        self.root_hlayout.addWidget(self.tablesTabWidget)
        self.gridLayout_2.addLayout(self.root_hlayout, 1, 1, 1, 1)
        self.status_HLayout = QtGui.QHBoxLayout()
        self.status_HLayout.setObjectName(_fromUtf8("status_HLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.status_HLayout.addWidget(self.label_2)
        self.fignumSPIN = QtGui.QSpinBox(self.centralwidget)
        self.fignumSPIN.setObjectName(_fromUtf8("fignumSPIN"))
        self.status_HLayout.addWidget(self.fignumSPIN)
        self.state_LBL = QtGui.QLabel(self.centralwidget)
        self.state_LBL.setObjectName(_fromUtf8("state_LBL"))
        self.status_HLayout.addWidget(self.state_LBL)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.status_HLayout.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.status_HLayout.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.status_HLayout.addWidget(self.label_3)
        self.sel_cid_SPIN = QtGui.QSpinBox(self.centralwidget)
        self.sel_cid_SPIN.setEnabled(False)
        self.sel_cid_SPIN.setObjectName(_fromUtf8("sel_cid_SPIN"))
        self.status_HLayout.addWidget(self.sel_cid_SPIN)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.status_HLayout.addWidget(self.label)
        self.sel_gid_SPIN = QtGui.QSpinBox(self.centralwidget)
        self.sel_gid_SPIN.setEnabled(False)
        self.sel_gid_SPIN.setObjectName(_fromUtf8("sel_gid_SPIN"))
        self.status_HLayout.addWidget(self.sel_gid_SPIN)
        self.gridLayout_2.addLayout(self.status_HLayout, 2, 1, 1, 1)
        mainSkel.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainSkel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExperimenal = QtGui.QMenu(self.menubar)
        self.menuExperimenal.setObjectName(_fromUtf8("menuExperimenal"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        mainSkel.setMenuBar(self.menubar)
        self.actionOpen_Database = QtGui.QAction(mainSkel)
        self.actionOpen_Database.setObjectName(_fromUtf8("actionOpen_Database"))
        self.actionSave_Database = QtGui.QAction(mainSkel)
        self.actionSave_Database.setObjectName(_fromUtf8("actionSave_Database"))
        self.actionImport_Images = QtGui.QAction(mainSkel)
        self.actionImport_Images.setObjectName(_fromUtf8("actionImport_Images"))
        self.actionOpen_Data_Directory = QtGui.QAction(mainSkel)
        self.actionOpen_Data_Directory.setObjectName(_fromUtf8("actionOpen_Data_Directory"))
        self.actionOpen_Source_Directory = QtGui.QAction(mainSkel)
        self.actionOpen_Source_Directory.setObjectName(_fromUtf8("actionOpen_Source_Directory"))
        self.actionTogEll = QtGui.QAction(mainSkel)
        self.actionTogEll.setEnabled(True)
        self.actionTogEll.setObjectName(_fromUtf8("actionTogEll"))
        self.actionUndockDisplay = QtGui.QAction(mainSkel)
        self.actionUndockDisplay.setObjectName(_fromUtf8("actionUndockDisplay"))
        self.actionTogPlt = QtGui.QAction(mainSkel)
        self.actionTogPlt.setObjectName(_fromUtf8("actionTogPlt"))
        self.actionHelpCMD = QtGui.QAction(mainSkel)
        self.actionHelpCMD.setObjectName(_fromUtf8("actionHelpCMD"))
        self.actionHelpGUI = QtGui.QAction(mainSkel)
        self.actionHelpGUI.setObjectName(_fromUtf8("actionHelpGUI"))
        self.actionAbout = QtGui.QAction(mainSkel)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelpWorkflow = QtGui.QAction(mainSkel)
        self.actionHelpWorkflow.setObjectName(_fromUtf8("actionHelpWorkflow"))
        self.actionTogPts = QtGui.QAction(mainSkel)
        self.actionTogPts.setObjectName(_fromUtf8("actionTogPts"))
        self.actionAdd_ROI = QtGui.QAction(mainSkel)
        self.actionAdd_ROI.setObjectName(_fromUtf8("actionAdd_ROI"))
        self.actionReselect_ROI = QtGui.QAction(mainSkel)
        self.actionReselect_ROI.setObjectName(_fromUtf8("actionReselect_ROI"))
        self.actionNext = QtGui.QAction(mainSkel)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionRemove_Chip = QtGui.QAction(mainSkel)
        self.actionRemove_Chip.setObjectName(_fromUtf8("actionRemove_Chip"))
        self.actionQuery = QtGui.QAction(mainSkel)
        self.actionQuery.setEnabled(True)
        self.actionQuery.setObjectName(_fromUtf8("actionQuery"))
        self.actionPrev = QtGui.QAction(mainSkel)
        self.actionPrev.setObjectName(_fromUtf8("actionPrev"))
        self.actionWriteLogs = QtGui.QAction(mainSkel)
        self.actionWriteLogs.setObjectName(_fromUtf8("actionWriteLogs"))
        self.actionOpen_Internal_Directory = QtGui.QAction(mainSkel)
        self.actionOpen_Internal_Directory.setObjectName(_fromUtf8("actionOpen_Internal_Directory"))
        self.actionPreferences = QtGui.QAction(mainSkel)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionQuit = QtGui.QAction(mainSkel)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConvertImage2Chip = QtGui.QAction(mainSkel)
        self.actionConvertImage2Chip.setEnabled(True)
        self.actionConvertImage2Chip.setObjectName(_fromUtf8("actionConvertImage2Chip"))
        self.actionBatch_Change_Name = QtGui.QAction(mainSkel)
        self.actionBatch_Change_Name.setObjectName(_fromUtf8("actionBatch_Change_Name"))
        self.actionReselect_Ori = QtGui.QAction(mainSkel)
        self.actionReselect_Ori.setObjectName(_fromUtf8("actionReselect_Ori"))
        self.actionAdd_Metadata_Property = QtGui.QAction(mainSkel)
        self.actionAdd_Metadata_Property.setObjectName(_fromUtf8("actionAdd_Metadata_Property"))
        self.actionAutoassign = QtGui.QAction(mainSkel)
        self.actionAutoassign.setObjectName(_fromUtf8("actionAutoassign"))
        self.actionRankErrorExpt = QtGui.QAction(mainSkel)
        self.actionRankErrorExpt.setObjectName(_fromUtf8("actionRankErrorExpt"))
        self.actionName_Consistency_Experiment = QtGui.QAction(mainSkel)
        self.actionName_Consistency_Experiment.setObjectName(_fromUtf8("actionName_Consistency_Experiment"))
        self.actionIncrease_ROI_Size = QtGui.QAction(mainSkel)
        self.actionIncrease_ROI_Size.setObjectName(_fromUtf8("actionIncrease_ROI_Size"))
        self.actionView_Docs = QtGui.QAction(mainSkel)
        self.actionView_Docs.setEnabled(True)
        self.actionView_Docs.setObjectName(_fromUtf8("actionView_Docs"))
        self.actionAutoassign_2 = QtGui.QAction(mainSkel)
        self.actionAutoassign_2.setObjectName(_fromUtf8("actionAutoassign_2"))
        self.menuFile.addAction(self.actionOpen_Database)
        self.menuFile.addAction(self.actionSave_Database)
        self.menuFile.addAction(self.actionImport_Images)
        self.menuFile.addAction(self.actionQuit)
        self.menuExperimenal.addAction(self.actionConvertImage2Chip)
        self.menuExperimenal.addAction(self.actionBatch_Change_Name)
        self.menuExperimenal.addSeparator()
        self.menuExperimenal.addAction(self.actionAdd_Metadata_Property)
        self.menuExperimenal.addAction(self.actionIncrease_ROI_Size)
        self.menuExperimenal.addSeparator()
        self.menuExperimenal.addAction(self.actionOpen_Data_Directory)
        self.menuExperimenal.addAction(self.actionOpen_Source_Directory)
        self.menuExperimenal.addAction(self.actionOpen_Internal_Directory)
        self.menuExperimenal.addSeparator()
        self.menuOptions.addAction(self.actionTogEll)
        self.menuOptions.addAction(self.actionTogPts)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionTogPlt)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionView_Docs)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWriteLogs)
        self.menuActions.addAction(self.actionQuery)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionAdd_ROI)
        self.menuActions.addAction(self.actionReselect_ROI)
        self.menuActions.addAction(self.actionReselect_Ori)
        self.menuActions.addAction(self.actionRemove_Chip)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionNext)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuExperimenal.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainSkel)
        self.tablesTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainSkel)

    def retranslateUi(self, mainSkel):
        mainSkel.setWindowTitle(QtGui.QApplication.translate("mainSkel", "HotSpotter", None, QtGui.QApplication.UnicodeUTF8))
        self.image_TBL.setSortingEnabled(True)
        self.tablesTabWidget.setTabText(self.tablesTabWidget.indexOf(self.image_view), QtGui.QApplication.translate("mainSkel", "Image Table", None, QtGui.QApplication.UnicodeUTF8))
        self.chip_TBL.setSortingEnabled(True)
        self.tablesTabWidget.setTabText(self.tablesTabWidget.indexOf(self.chip_view), QtGui.QApplication.translate("mainSkel", "Chip Table", None, QtGui.QApplication.UnicodeUTF8))
        self.res_TBL.setSortingEnabled(True)
        self.tablesTabWidget.setTabText(self.tablesTabWidget.indexOf(self.result_view), QtGui.QApplication.translate("mainSkel", "Results Table", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainSkel", "fignum: ", None, QtGui.QApplication.UnicodeUTF8))
        self.state_LBL.setText(QtGui.QApplication.translate("mainSkel", "State: Unloaded Gui State", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainSkel", "Image-ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainSkel", "Chip-ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mainSkel", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExperimenal.setTitle(QtGui.QApplication.translate("mainSkel", "Experimental", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("mainSkel", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("mainSkel", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("mainSkel", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Database.setText(QtGui.QApplication.translate("mainSkel", "Open Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Database.setShortcut(QtGui.QApplication.translate("mainSkel", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Database.setText(QtGui.QApplication.translate("mainSkel", "Save Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Database.setShortcut(QtGui.QApplication.translate("mainSkel", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Images.setText(QtGui.QApplication.translate("mainSkel", "Import Images", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Images.setShortcut(QtGui.QApplication.translate("mainSkel", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Data_Directory.setText(QtGui.QApplication.translate("mainSkel", "View Data Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Source_Directory.setText(QtGui.QApplication.translate("mainSkel", "View Source Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTogEll.setText(QtGui.QApplication.translate("mainSkel", "Toggle Ellipses", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTogEll.setShortcut(QtGui.QApplication.translate("mainSkel", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndockDisplay.setText(QtGui.QApplication.translate("mainSkel", "Undock Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTogPlt.setText(QtGui.QApplication.translate("mainSkel", "Toggle PlotWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpCMD.setText(QtGui.QApplication.translate("mainSkel", "Command Line Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpGUI.setText(QtGui.QApplication.translate("mainSkel", "GUI Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("mainSkel", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpWorkflow.setText(QtGui.QApplication.translate("mainSkel", "Workflow Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTogPts.setText(QtGui.QApplication.translate("mainSkel", "Toggle Points", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTogPts.setShortcut(QtGui.QApplication.translate("mainSkel", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_ROI.setText(QtGui.QApplication.translate("mainSkel", "Add ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_ROI.setShortcut(QtGui.QApplication.translate("mainSkel", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReselect_ROI.setText(QtGui.QApplication.translate("mainSkel", "Reselect ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReselect_ROI.setShortcut(QtGui.QApplication.translate("mainSkel", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("mainSkel", "Select Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("mainSkel", "Selects the next unidentified CID or Untagged GID", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setShortcut(QtGui.QApplication.translate("mainSkel", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Chip.setText(QtGui.QApplication.translate("mainSkel", "Remove Chip", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Chip.setShortcut(QtGui.QApplication.translate("mainSkel", "Ctrl+Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuery.setText(QtGui.QApplication.translate("mainSkel", "Query", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuery.setShortcut(QtGui.QApplication.translate("mainSkel", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrev.setText(QtGui.QApplication.translate("mainSkel", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWriteLogs.setText(QtGui.QApplication.translate("mainSkel", "Write Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Internal_Directory.setText(QtGui.QApplication.translate("mainSkel", "View Internal Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("mainSkel", "Edit Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setShortcut(QtGui.QApplication.translate("mainSkel", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("mainSkel", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvertImage2Chip.setText(QtGui.QApplication.translate("mainSkel", "Convert All Images to Chips", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBatch_Change_Name.setText(QtGui.QApplication.translate("mainSkel", "Batch Change Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReselect_Ori.setText(QtGui.QApplication.translate("mainSkel", "Reselect Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReselect_Ori.setShortcut(QtGui.QApplication.translate("mainSkel", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Metadata_Property.setText(QtGui.QApplication.translate("mainSkel", "Add Chip Property", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoassign.setText(QtGui.QApplication.translate("mainSkel", "Assign Matches Above Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRankErrorExpt.setText(QtGui.QApplication.translate("mainSkel", "Rank Error Experiment", None, QtGui.QApplication.UnicodeUTF8))
        self.actionName_Consistency_Experiment.setText(QtGui.QApplication.translate("mainSkel", "Name Consistency", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncrease_ROI_Size.setText(QtGui.QApplication.translate("mainSkel", "Increase all ROI Sizes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Docs.setText(QtGui.QApplication.translate("mainSkel", "View Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoassign_2.setText(QtGui.QApplication.translate("mainSkel", "Auto-Assign Matches", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainSkel = QtGui.QMainWindow()
    ui = Ui_mainSkel()
    ui.setupUi(mainSkel)
    mainSkel.show()
    sys.exit(app.exec_())

