# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Code\HotSpotter-python\widgets\MainWidget.ui'
#
# Created: Fri Mar 29 22:42:29 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName(_fromUtf8("MainWidget"))
        MainWidget.resize(927, 573)
        self.centralwidget = QtGui.QWidget(MainWidget)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.root_hlayout = QtGui.QHBoxLayout()
        self.root_hlayout.setObjectName(_fromUtf8("root_hlayout"))
        self.tablesTabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablesTabWidget.sizePolicy().hasHeightForWidth())
        self.tablesTabWidget.setSizePolicy(sizePolicy)
        self.tablesTabWidget.setObjectName(_fromUtf8("tablesTabWidget"))
        self.image_view = QtGui.QWidget()
        self.image_view.setMinimumSize(QtCore.QSize(445, 0))
        self.image_view.setObjectName(_fromUtf8("image_view"))
        self.gridLayout_3 = QtGui.QGridLayout(self.image_view)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.image_TBL = QtGui.QTableWidget(self.image_view)
        self.image_TBL.setObjectName(_fromUtf8("image_TBL"))
        self.image_TBL.setColumnCount(0)
        self.image_TBL.setRowCount(0)
        self.verticalLayout.addWidget(self.image_TBL)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tablesTabWidget.addTab(self.image_view, _fromUtf8(""))
        self.chip_view = QtGui.QWidget()
        self.chip_view.setObjectName(_fromUtf8("chip_view"))
        self.gridLayout_4 = QtGui.QGridLayout(self.chip_view)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.chip_TBL = QtGui.QTableWidget(self.chip_view)
        self.chip_TBL.setObjectName(_fromUtf8("chip_TBL"))
        self.chip_TBL.setColumnCount(0)
        self.chip_TBL.setRowCount(0)
        self.verticalLayout_3.addWidget(self.chip_TBL)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tablesTabWidget.addTab(self.chip_view, _fromUtf8(""))
        self.result_view = QtGui.QWidget()
        self.result_view.setObjectName(_fromUtf8("result_view"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.result_view)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.res_TBL = QtGui.QTableWidget(self.result_view)
        self.res_TBL.setObjectName(_fromUtf8("res_TBL"))
        self.res_TBL.setColumnCount(0)
        self.res_TBL.setRowCount(0)
        self.verticalLayout_4.addWidget(self.res_TBL)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tablesTabWidget.addTab(self.result_view, _fromUtf8(""))
        self.root_hlayout.addWidget(self.tablesTabWidget)
        self.gridLayout_2.addLayout(self.root_hlayout, 1, 1, 1, 1)
        self.status_HLayout = QtGui.QHBoxLayout()
        self.status_HLayout.setObjectName(_fromUtf8("status_HLayout"))
        self.state_LBL = QtGui.QLabel(self.centralwidget)
        self.state_LBL.setObjectName(_fromUtf8("state_LBL"))
        self.status_HLayout.addWidget(self.state_LBL)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.status_HLayout.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.status_HLayout.addWidget(self.label_3)
        self.sel_cid_SPIN = QtGui.QSpinBox(self.centralwidget)
        self.sel_cid_SPIN.setEnabled(False)
        self.sel_cid_SPIN.setObjectName(_fromUtf8("sel_cid_SPIN"))
        self.status_HLayout.addWidget(self.sel_cid_SPIN)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.status_HLayout.addWidget(self.label)
        self.sel_gid_SPIN = QtGui.QSpinBox(self.centralwidget)
        self.sel_gid_SPIN.setEnabled(False)
        self.sel_gid_SPIN.setObjectName(_fromUtf8("sel_gid_SPIN"))
        self.status_HLayout.addWidget(self.sel_gid_SPIN)
        self.gridLayout_2.addLayout(self.status_HLayout, 2, 1, 1, 1)
        MainWidget.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        MainWidget.setMenuBar(self.menubar)
        self.actionOpen_Database = QtGui.QAction(MainWidget)
        self.actionOpen_Database.setObjectName(_fromUtf8("actionOpen_Database"))
        self.actionSave_Database = QtGui.QAction(MainWidget)
        self.actionSave_Database.setObjectName(_fromUtf8("actionSave_Database"))
        self.actionImport_Images = QtGui.QAction(MainWidget)
        self.actionImport_Images.setObjectName(_fromUtf8("actionImport_Images"))
        self.actionOpen_Data_Directory = QtGui.QAction(MainWidget)
        self.actionOpen_Data_Directory.setObjectName(_fromUtf8("actionOpen_Data_Directory"))
        self.actionOpen_Source_Directory = QtGui.QAction(MainWidget)
        self.actionOpen_Source_Directory.setObjectName(_fromUtf8("actionOpen_Source_Directory"))
        self.actionTogEll = QtGui.QAction(MainWidget)
        self.actionTogEll.setObjectName(_fromUtf8("actionTogEll"))
        self.actionUndockDisplay = QtGui.QAction(MainWidget)
        self.actionUndockDisplay.setObjectName(_fromUtf8("actionUndockDisplay"))
        self.actionTogPlt = QtGui.QAction(MainWidget)
        self.actionTogPlt.setObjectName(_fromUtf8("actionTogPlt"))
        self.actionHelpCMD = QtGui.QAction(MainWidget)
        self.actionHelpCMD.setObjectName(_fromUtf8("actionHelpCMD"))
        self.actionHelpGUI = QtGui.QAction(MainWidget)
        self.actionHelpGUI.setObjectName(_fromUtf8("actionHelpGUI"))
        self.actionHelpTroubles = QtGui.QAction(MainWidget)
        self.actionHelpTroubles.setObjectName(_fromUtf8("actionHelpTroubles"))
        self.actionHelpWorkflow = QtGui.QAction(MainWidget)
        self.actionHelpWorkflow.setObjectName(_fromUtf8("actionHelpWorkflow"))
        self.actionTogPts = QtGui.QAction(MainWidget)
        self.actionTogPts.setObjectName(_fromUtf8("actionTogPts"))
        self.actionAdd_ROI = QtGui.QAction(MainWidget)
        self.actionAdd_ROI.setObjectName(_fromUtf8("actionAdd_ROI"))
        self.actionReselect_ROI = QtGui.QAction(MainWidget)
        self.actionReselect_ROI.setObjectName(_fromUtf8("actionReselect_ROI"))
        self.actionNext = QtGui.QAction(MainWidget)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionRemove_Chip = QtGui.QAction(MainWidget)
        self.actionRemove_Chip.setObjectName(_fromUtf8("actionRemove_Chip"))
        self.actionQuery = QtGui.QAction(MainWidget)
        self.actionQuery.setObjectName(_fromUtf8("actionQuery"))
        self.actionPrev = QtGui.QAction(MainWidget)
        self.actionPrev.setObjectName(_fromUtf8("actionPrev"))
        self.actionWriteLogs = QtGui.QAction(MainWidget)
        self.actionWriteLogs.setObjectName(_fromUtf8("actionWriteLogs"))
        self.actionOpen_Internal_Directory = QtGui.QAction(MainWidget)
        self.actionOpen_Internal_Directory.setObjectName(_fromUtf8("actionOpen_Internal_Directory"))
        self.menuFile.addAction(self.actionOpen_Database)
        self.menuFile.addAction(self.actionSave_Database)
        self.menuFile.addAction(self.actionImport_Images)
        self.menuView.addAction(self.actionOpen_Data_Directory)
        self.menuView.addAction(self.actionOpen_Source_Directory)
        self.menuView.addAction(self.actionOpen_Internal_Directory)
        self.menuOptions.addAction(self.actionTogEll)
        self.menuOptions.addAction(self.actionTogPts)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionTogPlt)
        self.menuHelp.addAction(self.actionHelpWorkflow)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelpCMD)
        self.menuHelp.addAction(self.actionHelpGUI)
        self.menuHelp.addAction(self.actionHelpTroubles)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWriteLogs)
        self.menuActions.addAction(self.actionQuery)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionAdd_ROI)
        self.menuActions.addAction(self.actionReselect_ROI)
        self.menuActions.addAction(self.actionRemove_Chip)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionNext)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWidget)
        self.tablesTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(_translate("MainWidget", "HotSpotter", None))
        self.image_TBL.setSortingEnabled(True)
        self.tablesTabWidget.setTabText(self.tablesTabWidget.indexOf(self.image_view), _translate("MainWidget", "Image Table", None))
        self.chip_TBL.setSortingEnabled(True)
        self.tablesTabWidget.setTabText(self.tablesTabWidget.indexOf(self.chip_view), _translate("MainWidget", "Chip Table", None))
        self.res_TBL.setSortingEnabled(True)
        self.tablesTabWidget.setTabText(self.tablesTabWidget.indexOf(self.result_view), _translate("MainWidget", "Results Table", None))
        self.state_LBL.setText(_translate("MainWidget", "State: Unloaded Gui State", None))
        self.label_3.setText(_translate("MainWidget", "Image-ID:", None))
        self.label.setText(_translate("MainWidget", "Chip-ID:", None))
        self.menuFile.setTitle(_translate("MainWidget", "File", None))
        self.menuView.setTitle(_translate("MainWidget", "View", None))
        self.menuOptions.setTitle(_translate("MainWidget", "Options", None))
        self.menuHelp.setTitle(_translate("MainWidget", "Help", None))
        self.menuActions.setTitle(_translate("MainWidget", "Actions", None))
        self.actionOpen_Database.setText(_translate("MainWidget", "Open Database", None))
        self.actionOpen_Database.setShortcut(_translate("MainWidget", "Ctrl+O", None))
        self.actionSave_Database.setText(_translate("MainWidget", "Save Database", None))
        self.actionSave_Database.setShortcut(_translate("MainWidget", "Ctrl+S", None))
        self.actionImport_Images.setText(_translate("MainWidget", "Import Images", None))
        self.actionImport_Images.setShortcut(_translate("MainWidget", "Ctrl+I", None))
        self.actionOpen_Data_Directory.setText(_translate("MainWidget", "View Data Directory", None))
        self.actionOpen_Source_Directory.setText(_translate("MainWidget", "View Source Directory", None))
        self.actionTogEll.setText(_translate("MainWidget", "Toggle HotSpot Ellipses", None))
        self.actionTogEll.setShortcut(_translate("MainWidget", "E", None))
        self.actionUndockDisplay.setText(_translate("MainWidget", "Undock Display", None))
        self.actionTogPlt.setText(_translate("MainWidget", "Toggle Plot Docking", None))
        self.actionHelpCMD.setText(_translate("MainWidget", "Command Line Help", None))
        self.actionHelpGUI.setText(_translate("MainWidget", "GUI Help", None))
        self.actionHelpTroubles.setText(_translate("MainWidget", "Troubleshooting", None))
        self.actionHelpWorkflow.setText(_translate("MainWidget", "Workflow Help", None))
        self.actionTogPts.setText(_translate("MainWidget", "Toggle HotSpot Points", None))
        self.actionTogPts.setShortcut(_translate("MainWidget", "P", None))
        self.actionAdd_ROI.setText(_translate("MainWidget", "Add ROI", None))
        self.actionAdd_ROI.setShortcut(_translate("MainWidget", "A", None))
        self.actionReselect_ROI.setText(_translate("MainWidget", "Reselect ROI", None))
        self.actionReselect_ROI.setShortcut(_translate("MainWidget", "R", None))
        self.actionNext.setText(_translate("MainWidget", "Select Next", None))
        self.actionNext.setToolTip(_translate("MainWidget", "Selects the next unidentified CID or Untagged GID", None))
        self.actionNext.setShortcut(_translate("MainWidget", "N", None))
        self.actionRemove_Chip.setText(_translate("MainWidget", "Remove Chip", None))
        self.actionRemove_Chip.setShortcut(_translate("MainWidget", "Ctrl+Del", None))
        self.actionQuery.setText(_translate("MainWidget", "Query", None))
        self.actionQuery.setShortcut(_translate("MainWidget", "Q", None))
        self.actionPrev.setText(_translate("MainWidget", "Prev", None))
        self.actionWriteLogs.setText(_translate("MainWidget", "Write Logs", None))
        self.actionOpen_Internal_Directory.setText(_translate("MainWidget", "View Internal Directory", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWidget = QtGui.QMainWindow()
    ui = Ui_MainWidget()
    ui.setupUi(MainWidget)
    MainWidget.show()
    sys.exit(app.exec_())

